In [1]:
import numpy as np

In [3]:
dizi = np.array([1,2,3])

In [5]:
dizi[0]

1

In [8]:
iki_boyutlu = np.array([[1,2,3], [4,5,6]])

In [9]:
iki_boyutlu

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
uc_boyutlu = np.array([1,2,[3,4,5,[6,7,8]]])

In [13]:
uc_boyutlu

array([1, 2, list([3, 4, 5, [6, 7, 8]])], dtype=object)

In [14]:
uc_boyutlu[2][3][1]

7

In [15]:
iki_boyutlu.ndim

2

In [16]:
uc_boyutlu.ndim

1

In [17]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.zeros((3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
uc_boyutlu=np.zeros((3,5,2), dtype=int)

In [21]:
uc_boyutlu.ndim

3

In [28]:
np.set_printoptions(precision=2)
np.full((3,5,2),np.pi,float)

array([[[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]]])

In [29]:
np.pi

3.141592653589793

In [30]:
np.linspace(start=0,stop=10,num=20,dtype=float)

array([ 0.  ,  0.53,  1.05,  1.58,  2.11,  2.63,  3.16,  3.68,  4.21,
        4.74,  5.26,  5.79,  6.32,  6.84,  7.37,  7.89,  8.42,  8.95,
        9.47, 10.  ])

In [33]:
np.random.random(size=10)*10

array([9.46, 1.97, 9.4 , 8.69, 2.26, 8.27, 0.81, 9.24, 3.9 , 2.76])

In [32]:
np.random.randint(low=5,high=25,size=10)

array([13,  9, 22,  9,  9, 12,  5, 19,  5,  9])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
""" Eğer her denemede aynı rassal değeri oluşturmak 
istersem numpy beslemesini(seed) değerini 
ayarlayabilirim"""

' Eğer her denemede aynı rassal değeri oluşturmak \nistersem numpy beslemesini(seed) değerini \nayarlayabilirim'

In [37]:
np.random.seed(0)
np.random.randint(0,10,size=10)

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [38]:
np.random.seed(0)
np.random.randint(0,10,size=10)

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [41]:
np.random.seed(1)
np.random.randint(0,10,size=10)

array([5, 8, 9, 5, 0, 0, 1, 7, 6, 9])

In [43]:
seed_1 = 0
seed_2 = 1
np.random.seed(seed_1)
np.random.randint(0,10,size=10)

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [44]:
x1 = np.random.randint(10, size=6) # Tek boyutlu dizi

In [45]:
x1

array([7, 6, 8, 8, 1, 6])

In [46]:
x2 = np.random.randint(10, size=(3, 4)) # iki boyutlu dizi
x2

array([[7, 7, 8, 1],
       [5, 9, 8, 9],
       [4, 3, 0, 3]])

In [47]:
x3 = np.random.randint(10, size=(3, 4, 5)) # üç boyutlu dizi

In [48]:
x3

array([[[5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7],
        [0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7]],

       [[2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1],
        [4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6]],

       [[7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4],
        [4, 3, 4, 4, 8],
        [4, 3, 7, 5, 5]]])

In [49]:
x3[2][3][2]

7

In [50]:
x3.ndim

3

In [51]:
x1 = np.random.randint(10, size=6) # Tek boyutlu dizi
x2 = np.random.randint(10, size=(3, 4)) # iki boyutlu dizi
x3 = np.random.randint(10, size=(3, 4, 5)) # üç boyutlu dizi

In [56]:
print("x3 dizisinin \nboyutu: {0}\nşekli: {2}\nbüyüklüğü: {1}\n veri tipi: {3}".format(x3.ndim, x3.shape, x3.size,x3.dtype))

x3 dizisinin 
boyutu: 3
şekli: (3, 4, 5)
büyüklüğü: 60
 veri tipi: int32


In [59]:
%precision 3

'%.3f'

In [60]:
np.pi

3.142

In [61]:
x1

array([0, 1, 5, 9, 3, 0])

In [62]:
x1[5]

0

In [63]:
x1[-1]

0

In [64]:
x1[-3]

9

In [67]:
x1[2:5:2]

array([5, 3])

In [68]:
x1[:-2]

array([0, 1, 5, 9])

In [69]:
x1[::-1]

array([0, 3, 9, 5, 1, 0])

In [70]:
x2

array([[5, 0, 1, 2],
       [4, 2, 0, 3],
       [2, 0, 7, 5]])

In [71]:
x2[:,2]

array([1, 0, 7])

In [72]:
x2[2,:]

array([2, 0, 7, 5])

In [73]:
x2[1:,:3]

array([[4, 2, 0],
       [2, 0, 7]])

In [74]:
x2[::-1,::-1]

array([[5, 7, 0, 2],
       [3, 0, 2, 4],
       [2, 1, 0, 5]])

In [75]:
# Dizi kopyalama

In [76]:
x2

array([[5, 0, 1, 2],
       [4, 2, 0, 3],
       [2, 0, 7, 5]])

In [77]:
x5 = x2

In [78]:
x5

array([[5, 0, 1, 2],
       [4, 2, 0, 3],
       [2, 0, 7, 5]])

In [79]:
x5[0][0]=2

In [80]:
x5

array([[2, 0, 1, 2],
       [4, 2, 0, 3],
       [2, 0, 7, 5]])

In [81]:
x2

array([[2, 0, 1, 2],
       [4, 2, 0, 3],
       [2, 0, 7, 5]])

In [82]:
x6 = x2.copy()

In [83]:
x6

array([[2, 0, 1, 2],
       [4, 2, 0, 3],
       [2, 0, 7, 5]])

In [84]:
x6[0,0] = 8

In [85]:
x6

array([[8, 0, 1, 2],
       [4, 2, 0, 3],
       [2, 0, 7, 5]])

In [86]:
x2

array([[2, 0, 1, 2],
       [4, 2, 0, 3],
       [2, 0, 7, 5]])

In [87]:
x2_kopya = x2[:2,:2].copy()

In [88]:
x2_kopya

array([[2, 0],
       [4, 2]])

In [90]:
x7 = np.arange(0,15,2)

In [91]:
x7.shape

(8,)

In [92]:
x7

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [98]:
x7=x7.reshape((2,4))

In [99]:
x7

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [107]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [106]:
print("x + 5 = {}".format(x+5))

x + 5 = [5 6 7 8]


In [108]:
print("x - 5 = {}".format(x-5))

x - 5 = [-5 -4 -3 -2]


In [112]:
x%2

array([0, 1, 0, 1], dtype=int32)

In [113]:
abs(x - 5)

array([5, 4, 3, 2])

In [114]:
np.sum(x)

6

In [125]:
np.percentile(x,q=75)

2.25

In [120]:
x

array([0, 1, 2, 3])

In [126]:
IQR = np.percentile(x,q=75)-np.percentile(x,q=25)

In [127]:
IQR

1.5

In [128]:
import pandas as pd

In [129]:
data = pd.read_csv("transactions.csv")

In [130]:
data.head()

Customer   TransDate  Quantity  PurchAmount    Cost
0    149332  15.11.2005         1       199.95  107.00
1    172951  29.08.2008         1       199.95  108.00
2    120621  19.10.2007         1        99.95   49.00
3    149236  14.11.2005         1        39.95   18.95
4    149236  12.06.2007         1        79.95   35.00

In [131]:
costs = np.array(data['Cost'])

In [135]:
costs.size

223191

In [136]:
costs.mean()

39.01329462209499

In [137]:
costs.std()

57.14497212662838

In [138]:
costs.max()

0.0

In [139]:
np.percentile(costs,q=25)

14.03

In [142]:
costs[costs < 39]

array([18.95, 35.  , 11.5 , ..., 13.8 , 13.8 , 10.5 ])

In [144]:
cost_sort = costs.sort()

In [145]:
cost_sort

In [147]:
np.sort(costs,axis=0)

array([   0.,    0.,    0., ..., 3080., 3100., 3100.])

In [ ]:
np.